# -*- coding: utf-8 -*-
"""chapter8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K4XU1ajIdm3SxM6WfXNq-8NcCtsOtR5S
"""

#DL for medicine
# Convolutional networks are an extraordinarily powerful tool, because so much
# human activity revolves around processing complex visual information.

# requires 80GB data download this is not feasible for me

# skipping this chapter, will come back to it later

